version: '3.9'

services:

  mqtt-broker:
    container_name: mosquitto-demo
    image: eclipse-mosquitto:latest
    restart: "no"
    ports:
      - "41883:1883"
      - "49001:9001"
    volumes:
      - "${WORKING_DIR:-.}/src/docker:/mosquitto/config:RO"
      - "${WORKING_DIR:-.}/target/docker-mosquitto/data:/mosquitto/data"
      - "${WORKING_DIR:-.}/target/docker-mosquitto/log:/mosquitto/log"
    stdin_open: true
    tty: true
