version: '3.9'

services:

  mqtt-broker:
    container_name: mosquitto-demo
    image: eclipse-mosquitto:latest
    restart: "no"
    ports:
      - "41883:1883"
      - "49001:9001"
    volumes:
      - "D:/projects/docker-mosquitto:/mosquitto"
      # - "D:/projects/docker-mosquitto/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      # - "D:/projects/docker-mosquitto/data:/mosquitto/data"
      # - "D:/projects/docker-mosquitto/log:/mosquitto/log"
    stdin_open: true
    tty: true
